//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPSProfessional.SharePoint.WebParts.SPSExplorer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SPSProfessional_SharePoint_WebParts_SPSExplorer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SPSProfessional_SharePoint_WebParts_SPSExplorer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SPSProfessional.SharePoint.WebParts.SPSExplorer.Resources.SPSProfessional.SharePo" +
                            "int.WebParts.SPSExplorer", typeof(SPSProfessional_SharePoint_WebParts_SPSExplorer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up Folder.
        /// </summary>
        internal static string SPS_UpFolderButton {
            get {
                return ResourceManager.GetString("SPS_UpFolderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string SPS_UploadButton {
            get {
                return ResourceManager.GetString("SPS_UploadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Number of Items in tree.
        /// </summary>
        internal static string SPSPE_CountItemsInTree {
            get {
                return ResourceManager.GetString("SPSPE_CountItemsInTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List:.
        /// </summary>
        internal static string SPSPE_ListName {
            get {
                return ResourceManager.GetString("SPSPE_ListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View not supported..
        /// </summary>
        internal static string SPSPE_NotSupportedView {
            get {
                return ResourceManager.GetString("SPSPE_NotSupportedView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Actions Button.
        /// </summary>
        internal static string SPSPE_ShowActionsButton {
            get {
                return ResourceManager.GetString("SPSPE_ShowActionsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show BreadCrumb.
        /// </summary>
        internal static string SPSPE_ShowBreadCrumb {
            get {
                return ResourceManager.GetString("SPSPE_ShowBreadCrumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show New Button.
        /// </summary>
        internal static string SPSPE_ShowNewButton {
            get {
                return ResourceManager.GetString("SPSPE_ShowNewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Tree.
        /// </summary>
        internal static string SPSPE_ShowTree {
            get {
                return ResourceManager.GetString("SPSPE_ShowTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Up Folder Button.
        /// </summary>
        internal static string SPSPE_ShowUpFolderButton {
            get {
                return ResourceManager.GetString("SPSPE_ShowUpFolderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Upload Button.
        /// </summary>
        internal static string SPSPE_ShowUploadButton {
            get {
                return ResourceManager.GetString("SPSPE_ShowUploadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Tree.
        /// </summary>
        internal static string SPSPE_SortHierarchyTree {
            get {
                return ResourceManager.GetString("SPSPE_SortHierarchyTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View:.
        /// </summary>
        internal static string SPSPE_ViewName {
            get {
                return ResourceManager.GetString("SPSPE_ViewName", resourceCulture);
            }
        }
    }
}
