//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4016
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPSProfessional.SharePoint.Events.SiteCreation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SPSProfessional_SharePoint_Events_SiteCreation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SPSProfessional_SharePoint_Events_SiteCreation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SPSProfessional.SharePoint.Events.SiteCreation.Resources.SPSProfessional.SharePoi" +
                            "nt.Events.SiteCreation", typeof(SPSProfessional_SharePoint_Events_SiteCreation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string BtnNextTitle {
            get {
                return ResourceManager.GetString("BtnNextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Site when delete item?.
        /// </summary>
        public static string chkOptAttachDeleteText {
            get {
                return ResourceManager.GetString("chkOptAttachDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a site with the same url than other, add a number to force the site creation..
        /// </summary>
        public static string chkOptForceCreationText {
            get {
                return ResourceManager.GetString("chkOptForceCreationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Template Field.
        /// </summary>
        public static string chkOptHideTemplateField {
            get {
                return ResourceManager.GetString("chkOptHideTemplateField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log error in the Url description field.
        /// </summary>
        public static string chkOptLogErrorText {
            get {
                return ResourceManager.GetString("chkOptLogErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display this site on the Quick Launch of the parent site?.
        /// </summary>
        public static string chkOptOnQuickLaunchText {
            get {
                return ResourceManager.GetString("chkOptOnQuickLaunchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use unique permissions.
        /// </summary>
        public static string chkOptUniquePermissonsText {
            get {
                return ResourceManager.GetString("chkOptUniquePermissonsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify whether this site shares the same top link bar as the parent. This setting may also determine the starting element of the breadcrumb..
        /// </summary>
        public static string chkOptUseSharedNavBarText {
            get {
                return ResourceManager.GetString("chkOptUseSharedNavBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Site.
        /// </summary>
        public static string DeleteSite {
            get {
                return ResourceManager.GetString("DeleteSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach another event handler to delete the site when the item is deleted..
        /// </summary>
        public static string DeleteSiteDescription {
            get {
                return ResourceManager.GetString("DeleteSiteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value specified for template not defined in TemplateMap.
        /// </summary>
        public static string ErrBadTemplateDefinition {
            get {
                return ResourceManager.GetString("ErrBadTemplateDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Management.
        /// </summary>
        public static string ErrorManagement {
            get {
                return ResourceManager.GetString("ErrorManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions to take when an error occurs when creating a new site..
        /// </summary>
        public static string ErrorManagementDescription {
            get {
                return ResourceManager.GetString("ErrorManagementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site title can´t be empty..
        /// </summary>
        public static string ErrSiteCantBeEmpty {
            get {
                return ResourceManager.GetString("ErrSiteCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields.
        /// </summary>
        public static string Fields {
            get {
                return ResourceManager.GetString("Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the three fields that the event handler needs..
        /// </summary>
        public static string FieldsDescription {
            get {
                return ResourceManager.GetString("FieldsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force creation.
        /// </summary>
        public static string ForceCreation {
            get {
                return ResourceManager.GetString("ForceCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach new list.
        /// </summary>
        public static string idAddKeyButtonText {
            get {
                return ResourceManager.GetString("idAddKeyButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach the SiteCreation event to a new list.
        /// </summary>
        public static string idAddKeyButtonToolTip {
            get {
                return ResourceManager.GetString("idAddKeyButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a list to attach the event handler. The list must have at least three fields. A text field which will contain the web name, a hyperlink field which will store the new created web Url and a choice field which will select a template.
        /// </summary>
        public static string ListDescription {
            get {
                return ResourceManager.GetString("ListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Id.
        /// </summary>
        public static string listID {
            get {
                return ResourceManager.GetString("listID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Name.
        /// </summary>
        public static string listName {
            get {
                return ResourceManager.GetString("listName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Error.
        /// </summary>
        public static string LogError {
            get {
                return ResourceManager.GetString("LogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Site Navigation.
        /// </summary>
        public static string NewSiteNavigation {
            get {
                return ResourceManager.GetString("NewSiteNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a site with the same url than other, add a number to force the site creation..
        /// </summary>
        public static string NewSiteNavigationDescription {
            get {
                return ResourceManager.GetString("NewSiteNavigationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Site Permissions.
        /// </summary>
        public static string NewSitePermissions {
            get {
                return ResourceManager.GetString("NewSitePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can create a site with the same permissions as the parent site or a site with unique permissions breaking the inheritance role. Additionally you can specify a list of groups that you want to add to the new site. Use the next syntax, 
        /// GROUP:Description;OTHERGROUP:Description.
        /// </summary>
        public static string NewSitePermissionsDescription {
            get {
                return ResourceManager.GetString("NewSitePermissionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select List.
        /// </summary>
        public static string SelectList {
            get {
                return ResourceManager.GetString("SelectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this page to attach the SPSProfessional Site Creation Event handler to any list in your site..
        /// </summary>
        public static string siteCreationPageDescription {
            get {
                return ResourceManager.GetString("siteCreationPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Name Field.
        /// </summary>
        public static string SiteNameField {
            get {
                return ResourceManager.GetString("SiteNameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Url Field.
        /// </summary>
        public static string SiteUrlField {
            get {
                return ResourceManager.GetString("SiteUrlField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Field.
        /// </summary>
        public static string TemplateField {
            get {
                return ResourceManager.GetString("TemplateField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        public static string Templates {
            get {
                return ResourceManager.GetString("Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build the template map, select a template for each option that you have defined in the choice field..
        /// </summary>
        public static string TemplatesDescription {
            get {
                return ResourceManager.GetString("TemplatesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups to Add to the new site.
        /// </summary>
        public static string txtOptNewPermissionsTitle {
            get {
                return ResourceManager.GetString("txtOptNewPermissionsTitle", resourceCulture);
            }
        }
    }
}
