//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPSProfessional.Actions.CopyPaste.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SPSProfessional_Actions_CopyPaste {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SPSProfessional_Actions_CopyPaste() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SPSProfessional.Actions.CopyPaste.Resources.SPSProfessional.Actions.CopyPaste", typeof(SPSProfessional_Actions_CopyPaste).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unselect all selected images..
        /// </summary>
        internal static string ClearSelectedMenuActionDescription {
            get {
                return ResourceManager.GetString("ClearSelectedMenuActionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unselect All.
        /// </summary>
        internal static string ClearSelectedMenuActionText {
            get {
                return ResourceManager.GetString("ClearSelectedMenuActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Document..
        /// </summary>
        internal static string CopyContextMenuDescription {
            get {
                return ResourceManager.GetString("CopyContextMenuDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string CopyContextMenuText {
            get {
                return ResourceManager.GetString("CopyContextMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy selected images..
        /// </summary>
        internal static string CopyImageMenuActionDescription {
            get {
                return ResourceManager.GetString("CopyImageMenuActionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string CopyImageMenuActionText {
            get {
                return ResourceManager.GetString("CopyImageMenuActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut Document..
        /// </summary>
        internal static string CutContextMenuDescription {
            get {
                return ResourceManager.GetString("CutContextMenuDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string CutContextMenuText {
            get {
                return ResourceManager.GetString("CutContextMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut selected images..
        /// </summary>
        internal static string CutImageMenuActionDescription {
            get {
                return ResourceManager.GetString("CutImageMenuActionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string CutImageMenuActionText {
            get {
                return ResourceManager.GetString("CutImageMenuActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Documents..
        /// </summary>
        internal static string PasteFileMenuActionDescription {
            get {
                return ResourceManager.GetString("PasteFileMenuActionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Images..
        /// </summary>
        internal static string PasteImageMenuActionDescription {
            get {
                return ResourceManager.GetString("PasteImageMenuActionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string PasteMenuActionText {
            get {
                return ResourceManager.GetString("PasteMenuActionText", resourceCulture);
            }
        }
    }
}
